### ISSUE TITLE
Add overview page to Atomium base theme

### ISSUE THREAD

**Issue by ademarco** [ec-europa/atomium#10]
### Scope
It would  be useful to have  a page listing all components that needs style, this will be then helpful when applying styles coming from the component library.

### Tasks
- [ ] Make sure each template / component can expose meta information about itself
- [ ] Make sure each template / component can provide example data useful for rendering
- [ ] Build overview page

**Comment by ademarco** [comment]
We might expose metadata concerning a component in the following way:

```php
/**
 * Implements atomium_overview__hook().
 */
function atomium_overview__block() {
  return array(
    'label' => 'Button',
    'description' => 'Button template',
    'preview' => array(
      'element' => array(
        '#value' => 'Save',
        '#type' => 'submit',
      ),
    ),
  );
}
```

**Comment by drupol** [comment]
👍
